# permissions for end users to edit dummies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dummy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: d-op
    app.kubernetes.io/part-of: d-op
    app.kubernetes.io/managed-by: kustomize
  name: dummy-editor-role
rules:
- apiGroups:
  - homework.anynines.com
  resources:
  - dummies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homework.anynines.com
  resources:
  - dummies/status
  verbs:
  - get
